packages:
  - apps/*
  - packages/*

overrides:
  '@testmaker/ui>react-dom': ^19.3.0

allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  tesseract.js: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - zod@4.6.5
  - lucide-react@1.46.0
  - '@ai-sdk/google@4.0.72'
  - '@ai-sdk/provider-utils@5.0.41'
  - '@ai-sdk/provider@4.0.15'
  - '@ai-sdk/openai-compatible@3.0.49'

patchedDependencies:
  fontkit@2.0.4: patches/fontkit@2.0.4.patch
