import { z } from 'zod'
import { t } from '../i18n'
import { normalizeGeneratedQuestion, questionContentSchema, type QuestionContent } from '../schema/question'
import { checkQuestion, duplicateCheck, withDefaultPoints } from './generate'
import { buildSystemPrompt, QUESTION_TYPE_HINTS } from './prompts/questions'

/**
 * Questions from Claude Code. The Claude Max subscription cannot be used in
 * the app, but it can in Claude Code: the owner downloads the topic's
 * materials as text, has the questions written with the `/otazky` command and
 * uploads the file back to the topic. The check is the same as for generation
 * in the app (`checkQuestion`), only the types are not restricted — Claude
 * handles matching and ordering too.
 *
 * The `# …` header lines of the source file are a file format read back by
 * the parsers below (and by `/otazky`), so they stay fixed in code.
 */
export const CLAUDE_CODE_MODEL = 'claude-code'

const EXISTING_HEADER = '# Otázky, které už v tématu jsou — nepiš je znovu:'
const RULES_HEADER = '# Pravidla školy:'

/**
 * Topic text for Claude Code: a header with the grade, existing questions and
 * school rules, then the materials. Rules get into the downloadable file this
 * way, not via `buildQuestionRules` — that script has no database
 * (`otazky:pravidla`), so it knows nothing about the school; this file is
 * generated by the school, so it can fetch the active rules itself.
 */
export function buildTopicSourceFile(meta: {
  subjectName: string
  gradeName: string | null
  topicName: string
  text: string
  existing: string[]
  schoolRules?: string[]
}): string {
  const lines = [
    `# Předmět: ${meta.subjectName}`,
    `# Ročník: ${meta.gradeName || 'neurčen'}`,
    `# Téma: ${meta.topicName}`,
  ]
  if (meta.schoolRules && meta.schoolRules.length > 0) {
    lines.push(RULES_HEADER, ...meta.schoolRules.map((rule) => `# - ${rule.replace(/\s+/g, ' ').trim()}`))
  }
  if (meta.existing.length > 0) {
    lines.push(EXISTING_HEADER, ...meta.existing.map((prompt) => `# - ${prompt.replace(/\s+/g, ' ').trim()}`))
  }
  lines.push('', meta.text)
  return lines.join('\n')
}

/** School rules from the header of the downloaded file — for `/otazky` in Claude Code. */
export function schoolRulesFromSource(source: string): string[] {
  const lines = source.split('\n')
  const start = lines.indexOf(RULES_HEADER)
  if (start === -1) return []
  const rules: string[] = []
  for (const line of lines.slice(start + 1)) {
    if (!line.startsWith('# - ')) break
    rules.push(line.slice(4))
  }
  return rules
}

/** Existing questions from the header of the source file. */
export function existingPromptsFromSource(source: string): string[] {
  const lines = source.split('\n')
  const start = lines.indexOf(EXISTING_HEADER)
  if (start === -1) return []
  const prompts: string[] = []
  for (const line of lines.slice(start + 1)) {
    if (!line.startsWith('# - ')) break
    prompts.push(line.slice(4))
  }
  return prompts
}

/**
 * Materials from the downloaded file without the `# …` header. On upload,
 * quotes are checked against the topic's materials themselves, not the
 * header — the haystack here must be the same, otherwise a check outside the
 * app would accept a quote from the header that the upload then rejects. A
 * file without a header is returned whole.
 */
export function materialFromSource(source: string): string {
  const lines = source.split('\n')
  if (!lines[0]?.startsWith('# Předmět:')) return source
  let i = 0
  while (lines[i]?.startsWith('# ')) i++
  return lines.slice(lines[i] === '' ? i + 1 : i).join('\n')
}

/**
 * Rules for writing questions: the same system prompt as in the app, the
 * types and the exact shape (JSON Schema). The `otazky:pravidla` script has
 * no database, so it never passes `schoolRules` — school rules reach Claude
 * Code through the header of the downloaded file (`buildTopicSourceFile`);
 * this parameter exists only so the call with rules stays testable.
 */
export function buildQuestionRules(gradeName: string | null, schoolRules: string[] = []): string {
  const types = Object.entries(QUESTION_TYPE_HINTS)
    .filter(([type]) => type !== 'label_image')
    .map(([type, hint]) => `- ${type}: ${hint}`)
  return [
    buildSystemPrompt(gradeName, schoolRules),
    '',
    'Typy otázek (label_image nepoužívej):',
    ...types,
    '',
    'Soubor je JSON ve tvaru { "questions": [ … ] }, každá otázka odpovídá tomuto schématu:',
    // `io: 'input'` — the `matching` schema contains a transform (`pairs`), and
    // without this option `toJSONSchema` rejects it, same as in `ai.test.ts`.
    JSON.stringify(z.toJSONSchema(questionContentSchema, { io: 'input' }), null, 2),
  ].join('\n')
}

/**
 * Error in the content of the question file (invalid JSON, missing
 * "questions" list), not in the database or elsewhere in the app. The route
 * handler recognises by this class that it is a file the teacher should fix
 * in Claude Code, and may safely show it as a user message — other exceptions
 * (e.g. from the database) cannot be told apart this way and must not be
 * mistaken for a file error.
 */
export class QuestionFileError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'QuestionFileError'
  }
}

/**
 * Reads the question file and keeps only those that pass the shape check,
 * the verbatim quote check (against the source text) and the duplicate check
 * — within the file and against questions already in the topic.
 */
export function readQuestionFile(
  json: string,
  source: string,
  existing: string[] = [],
): { questions: QuestionContent[]; rejected: { index: number; errors: string[] }[] } {
  let raw: unknown
  try {
    raw = JSON.parse(json)
  } catch {
    throw new QuestionFileError(t('ai:questionFile.invalidJson'))
  }
  const list = Array.isArray(raw)
    ? raw
    : Array.isArray((raw as { questions?: unknown })?.questions)
      ? (raw as { questions: unknown[] }).questions
      : null
  if (!list) throw new QuestionFileError(t('ai:questionFile.missingList'))

  const isDuplicate = duplicateCheck(existing)
  const questions: QuestionContent[] = []
  const rejected: { index: number; errors: string[] }[] = []

  list.forEach((candidate, index) => {
    const parsed = questionContentSchema.safeParse(candidate)
    if (!parsed.success) {
      rejected.push({ index, errors: parsed.error.issues.map((i) => `${i.path.join('.') || t('ai:questionFile.questionPath')}: ${i.message}`) })
      return
    }
    if (parsed.data.type === 'label_image') {
      rejected.push({ index, errors: [t('ai:questionFile.labelImageUnsupported')] })
      return
    }
    const errors = checkQuestion(parsed.data, source)
    if (errors.length > 0) {
      rejected.push({ index, errors })
      return
    }
    const question = withDefaultPoints(normalizeGeneratedQuestion(parsed.data))
    if (isDuplicate(question)) {
      rejected.push({ index, errors: [t('ai:questionFile.duplicate')] })
      return
    }
    questions.push(question)
  })

  return { questions, rejected }
}
